name: dister
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  flutter_dotenv: ^5.2.1
  animated_hint_textfield: ^1.0.3
  shared_preferences: ^2.5.1


  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  sidebarx: ^0.17.1
  crystal_navigation_bar: ^1.0.2
  cloud_firestore: ^5.6.4
  auto_size_text: ^3.0.0
  step_progress_indicator: ^1.0.2
  image_picker: ^1.1.2
  flutter_datetime_picker_plus: ^2.2.0
  confirmation_success: ^0.0.2
  firebase_storage: ^12.4.4
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  translator: ^1.0.3+1
  flutter_bloc: ^9.1.0



#flutter pub run flutter_native_splash:create si se modifica
flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#FFFEEA"
  image: "assets/images/logo.png"
  branding: "assets/images/branding.png"

  color_dark: "#212020"

  android_12:
    color: "#FFFEEA"
    image: "assets/images/logo.png"
    branding: "assets/images/branding.png"

    color_dark: "#212020"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  intl_utils: ^2.8.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/images/intropage/
    - assets/images/form_logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  class_name: S
  main_local: en
